// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGqq3n8qasjWXMgSUPd-RbfChWA8ec_TU',
    appId: '1:71402755662:web:fc117c43f2a11a2a7d151f',
    messagingSenderId: '71402755662',
    projectId: 'flutter-apps-d93d4',
    authDomain: 'flutter-apps-d93d4.firebaseapp.com',
    storageBucket: 'flutter-apps-d93d4.appspot.com',
    measurementId: 'G-N5YR8J1TKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8aghWhYtXQGilt0VLNprSRx9pjzJQbyY',
    appId: '1:71402755662:android:b130f7b4db3c2e5f7d151f',
    messagingSenderId: '71402755662',
    projectId: 'flutter-apps-d93d4',
    storageBucket: 'flutter-apps-d93d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_toge-ilTgrXUDaR5CEIN-CrbiE0gYes',
    appId: '1:71402755662:ios:3836f3c07c36ebc87d151f',
    messagingSenderId: '71402755662',
    projectId: 'flutter-apps-d93d4',
    storageBucket: 'flutter-apps-d93d4.appspot.com',
    iosClientId: '71402755662-ko63g8tlgn8m27t9kjhtklq58kev8r89.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_toge-ilTgrXUDaR5CEIN-CrbiE0gYes',
    appId: '1:71402755662:ios:3836f3c07c36ebc87d151f',
    messagingSenderId: '71402755662',
    projectId: 'flutter-apps-d93d4',
    storageBucket: 'flutter-apps-d93d4.appspot.com',
    iosClientId: '71402755662-ko63g8tlgn8m27t9kjhtklq58kev8r89.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
